version: "3.3"
services:
  server:
    container_name: stremio_server
    image: stremio/server:latest
    ports:
      - 11470:11470
      - 12470:12470
    volumes:
      - /bin/ffmpeg:/bin/ffmpeg:ro
      - /bin/ffprobe:/bin/ffprobe:ro
    environment:
      - FFMPEG_BIN=/usr/lib/jellyfin-ffmpeg/ffmpeg
      - FFPROBE_BIN=/usr/lib/jellyfin-ffmpeg/ffprobe
      # Uncomment and set value as needed
      #- APP_PATH=""
      - NO_CORS=1 
    restart: unless-stopped
